### ISSUE TITLE
Labs 5-6 assessment

### ISSUE THREAD

**Issue by grammarware** [OlavTrauschke/Software_testing_ft_7#5]
Week 5: great to see how you struggle not only with puzzle solving itself, but with the infrastructure around it; true software engineers :+1:. I believe you’ve made the right call to settle for a config.

Week 5: also kudos for investigating the number of empty blocks — things like this are quite typically provable formally. IRL as a software engineer it’s not your job to prove it, but it is to make use of the proofs by others.

Week 6: seems like Floris won the performance battle.

Week 6: the bonus solution is slightly disappointing in its unreachability — I had to write my own wrapper functions to try it out, let alone test it. But it’s there, so you got that going for you, which is nice.

Weeks 5 and 6 are :heavy_plus_sign::heavy_plus_sign: each.

**Comment by JordyHeemskerk** [comment]
Not that I'm complaining about the ++ :smile:, but whats wrong with the following function?
rsaDemo :: Int -> Int -> Integer -> IO (), it even has documentation above it, and an example below :smirk:

**Comment by grammarware** [comment]
I want `rsaDemo :: String -> IO ()` :blush:

**Comment by JordyHeemskerk** [comment]
Point taken.. :laughing:
